apiVersion: v1
data:
  .dockerconfigjson: {{- include "carshop.imageCredential" . | indent 1}}
kind: Secret
metadata:
  creationTimestamp: "2023-02-05T02:33:18Z"
  name: regcred
  resourceVersion: "90420"
  uid: 6b9e2b48-2c0b-44cc-a0db-42b907ed74a6
type: kubernetes.io/dockerconfigjson

